### ISSUE TITLE
input 输入框无法得到焦点

### ISSUE THREAD

**Issue by hzhijun** [asyndesis/react-highlight-menu#2]
在 menu 中返回一个 input 输入框，选择文本后弹出 input 输入框，但输入框入法输入内容

**Comment by asyndesis** [comment]
谢谢你指出这一点。我需要增加对输入和文本框的支持。 明天再来看看，我将尝试推送一个修正。

**Comment by asyndesis** [comment]
@hzhijun -

对不起，耽搁了。1.04版中增加了有限的文本区域和输入支持。
