### ISSUE TITLE
Firefox Compatibility

### ISSUE THREAD

**Issue by ben-hb** [asyndesis/react-highlight-menu#3]
The menu doesn't appear upon highlight in Firefox. I'm guessing this is related to Firefox's esoteric getSelection method, I know developers for a while have had to use selectionStart and selectionEnd instead of getSelection.toString. Would dearly appreciate a fix! 

FWIW I also encountered issues on IE (demo page wouldn't even load) but may not be too reliable as I was testing on a VM from BrowserStack. Works great on all other browsers I've tested (Opera, Chrome, Vivaldi, Edge, Safari).

**Comment by asyndesis** [comment]
Sorry @ben-hb -

I was on vacation and didn't see this.

Thanks for the solid Issue Posting.  Made it easy to find a [fix].

Doesn't look like `baseNode` is a property of selection anymore:
https://developer.mozilla.org/en-US/docs/Web/API/Selection/anchorNode

(ce1fa0e3d64b6cf43d2471c3d6355977e88c5cff).
